OT275-72: Endpoint Actualizacion de Miembros
alkemyTech/OT275-server pull request #100
Opened 2022-09-19 20:35 UTC by Sieglind

# [OT275-72](https://alkemy-labs.atlassian.net/browse/OT275-72)

Implemented member actualization endpoint at PUT /members/{id}

### HOW HAS THIS BEEN TESTED?

Unit tests and Postman requests were used to test this feature

- [ ] Postman.
- [ ] Unit test.
- [ ] Integration test.
- [ ] No testing required (only applies for tech task).

**Test Configuration**:

No additional configuration was needed in order to run these tests

**Screenshots**:
Given a member entry in the database:
![image](https://user-images.githubusercontent.com/73443385/191111318-79923fd4-93d8-4b9b-ad85-dfdccf83f15e.png)
When a PUT request is sent to the endpoint:
![image](https://user-images.githubusercontent.com/73443385/191111439-c6536617-4eaf-47f8-b98b-f6d4186ca20b.png)
The results can be seen in the database:
![image](https://user-images.githubusercontent.com/73443385/191111505-e829cf00-302d-4252-99b9-d154b4b5b500.png)
When an incorrect body format is sent, validations take place:
![image](https://user-images.githubusercontent.com/73443385/191111613-88bc5efd-6c4c-49bc-ae24-e0ba278c25d3.png)

### CHECKLIST

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added the new resource in the Postman Collection file.

2022-09-19 20:45 UTC, mkain0 requested changes

2022-09-19 20:45 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/resource/MemberResource.java
> +      @Valid @RequestBody CreateMemberRequest request) {
Al inicio del proyecto, se definió que los request body eran una clase por operación, no se reutiliza la clase. Por lo tanto, aquí debería haber un UpdateMemberRequest.

2022-09-19 21:09 UTC, Sieglind commented on src/main/java/com/alkemy/ong/infrastructure/rest/resource/MemberResource.java
> +      @Valid @RequestBody CreateMemberRequest request) {
Aunque tengan los mismos campos?

2022-09-19 21:52 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/resource/MemberResource.java
> +      @Valid @RequestBody CreateMemberRequest request) {
Si Sr. Lo conversamos allá a lo lejos del inicio de la aceleración cuando les dije que podían reutilizar los DTOs o crear uno por operación y decidieron: option 2

2022-09-19 21:54 UTC, mkain0 requested changes

2022-09-19 21:54 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/response/member/UpdateMemberResponse.java
> +public class UpdateMemberResponse extends GetMemberResponse {
Hace esto es una clara demostración de que no se require la existencia de updateMemberResponse. 

GetMemberResponse es la response del servicio y UpdateMemberRequest la request del servicio aunque tenga los mismos campos y misma validaciones. Ver otros servicios para referencia.

2022-09-19 22:16 UTC, Sieglind commented on src/main/java/com/alkemy/ong/infrastructure/rest/response/member/UpdateMemberResponse.java
> +public class UpdateMemberResponse extends GetMemberResponse {
Lei tan mal que termine cambiando cualquier cosa, disculpas

2022-09-20 08:14 UTC, mkain0 approved these changes

2022-09-20 08:14 UTC, merged