Ot275 45: endpoint eliminación de categorías
alkemyTech/OT275-server pull request #23
Opened 2022-08-27 20:30 UTC by FedericoRohr

# [Ot275-45](https://alkemy-labs.atlassian.net/browse/Ot275-45)

-Added delete of categories
-classes added : IDeleteCategoryUseCase , DeleteCategoryUseCase,CategoryResourse.
-added repository methods exists and delete (does softdelete)
-Unit test added

### HOW HAS THIS BEEN TESTED?

Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration.

- [X ] Postman.
- [X ] Unit test.
- [ ] Integration test.
- [ ] No testing required (only applies for tech task).

**Test Configuration**:

* ...
* ...

**Screenshots**:
![image](https://user-images.githubusercontent.com/104379574/187046922-72556fa1-1aac-4fb8-ab3a-7008d85f4da9.png)
![image](https://user-images.githubusercontent.com/104379574/187046926-e5459c6a-aff9-4516-a0fe-24250746a6e5.png)
![image](https://user-images.githubusercontent.com/104379574/187046930-e04c2786-e4df-451b-b353-5efc54bee41f.png)
![image](https://user-images.githubusercontent.com/104379574/187046931-5c481155-5e0d-4a38-9694-86ddeca99728.png)

* ....

### CHECKLIST

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added the new resource in the Postman Collection file.

2022-08-27 20:59 UTC, mkain0 requested changes
Por favor, resolver los merge conflicts antes de volver a solicitar review.

2022-08-27 20:59 UTC, mkain0 commented on src/test/java/com/alkemy/ong/application/service/DeleteCategoryUseCaseServiceTest.java
> +public class DeleteCategoryUseCaseServiceTest {
El modificador de acceso `public` no es necesario en este contexto.

2022-08-27 20:59 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/database/repository/abstraction/ICategorySpringRepository.java
> +      + "WHERE C.softDeleted = false AND C.categoryId = :id")
c minúscula para ser consistente con los el código de los otros repositorios.

2022-08-27 22:26 UTC, FedericoRohr commented
solucionando los merge conflict encontre que faltaba una "d" en la entity de members. Tuve que agregarla para poder pushear mi  ticket

2022-08-29 08:20 UTC, mkain0 approved these changes

2022-08-29 08:21 UTC, merged