OT275-79: Endpoint Eliminación Comentarios
alkemyTech/OT275-server pull request #25
Opened 2022-08-28 02:10 UTC by ezevillafae

# [OT275-79](https://alkemy-labs.atlassian.net/browse/OT275-79)

I added the functionality to delete comments, mappers and permissions to delete logic were also added.

### HOW HAS THIS BEEN TESTED?

- [x] Postman.
- [x] Unit test.
- [ ] Integration test.
- [ ] No testing required (only applies for tech task).

**Screenshots**:
![image](https://user-images.githubusercontent.com/40841894/187054337-f2046165-2d17-4b4a-bc2c-9f0fe6d5c6d1.png)

![image](https://user-images.githubusercontent.com/40841894/187054334-911d45d4-97a1-45de-88e6-b78328d8947c.png)

![image](https://user-images.githubusercontent.com/40841894/187054335-a5dce36e-0644-42a5-a969-6613d1fe26f5.png)

![image](https://user-images.githubusercontent.com/40841894/187054336-d7c96500-5e17-49c7-a0b7-9361faf56966.png)

* ....

### CHECKLIST

- [x] My code follows the style guidelines of this project.
- [x]I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] I have added the new resource in the Postman Collection file.

2022-08-28 02:12 UTC, ezevillafae commented
Al corregir los merge conflict tuve que arreglar el mismo problema que @FedericoRohr https://github.com/alkemyTech/OT275-server/pull/23#issuecomment-1229279804

2022-08-29 09:24 UTC, mkain0 requested changes

2022-08-29 09:24 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/usecase/IAuthorization.java
> +public interface IAuthorization {
Qué otros métodos tendría esta interfaz? Se va a utilizar para agregar métodos del login? Por ejemplo, para wrappear el authenticationManager#authenticate.

Si se va a reutilizar para el login, creo que deberíamos renombrarla a IAccessLayer o similar. Caso contrario, si solo la vamos a utilizar para saber si una operación esta permitida quizás deberíamos renombrar la interfaz a IOperationAllowed.

2022-08-29 09:24 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/config/spring/security/common/CommentAuthorization.java
> +    Optional<CommentResponse> commentResponse = comment.map(commentMapper::toResponse);
Este mapeo no es necesario. El response es solo necesario cuando se quiere enviar algo desde la capa de Resource al Usuario final.

2022-08-29 09:24 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/config/spring/security/common/CommentAuthorization.java
> +    return authentication.getName().equals(response.getUser().getEmail());
Se deberían comparar dos objetos User para hacer uso de POO.

2022-08-29 09:24 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/mapper/CommentMapper.java
> +public class CommentMapper {
Este Mapper no es necesario. Ver comentario en src/main/java/com/alkemy/ong/infrastructure/config/spring/security/common/CommentAuthorization.java

2022-08-29 09:24 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/mapper/UserMapper.java
> +public class UserMapper {
Este Mapper no es necesario. Ver comentario en src/main/java/com/alkemy/ong/infrastructure/config/spring/security/common/CommentAuthorization.java

2022-08-29 09:24 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/response/CommentResponse.java
> +public class CommentResponse {
Esta clase no es necesaria. Ver comentario en src/main/java/com/alkemy/ong/infrastructure/config/spring/security/common/CommentAuthorization.java

2022-08-29 09:24 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/response/UserResponse.java
> +public class UserResponse {
Esta clase no es necesaria. Ver comentario en src/main/java/com/alkemy/ong/infrastructure/config/spring/security/common/CommentAuthorization.java

2022-08-29 09:24 UTC, mkain0 commented on src/main/java/com/alkemy/ong/domain/Comment.java
> +  private User user;
Renombraría el nombre de esta variable a createdBy.

2022-08-29 18:37 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/DeleteCommentUseCaseService.java
> +      throw new OperationNotPermitted(ErrorMessage.OPERATION_NOT_PERMITTED.name());
MINOR: OPERATION_NOT_PERMITTED.name() devuelve OPERATION_NOT_PERMITTED. Debería ser #getMessage()

2022-08-29 18:37 UTC, mkain0 commented on src/test/java/com/alkemy/ong/application/service/DeleteCommentUseCaseServiceTest.java
> +    given(repository.exists(identifiable)).willReturn(false);
when y given cumplen la misma función solo que pertenecen a diferentes librerías. Tratar de utilizar siempre la misma en el contexto de cada unit test.

2022-08-29 18:37 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/config/spring/security/common/CommentDeleteOperationAllowed.java
> +    return user;
Viendolo sin el response object, no es necesario comparar utilizando POO :)

2022-08-29 18:38 UTC, mkain0 approved these changes

2022-08-29 18:38 UTC, merged