Ot275 40: Servicio reutilizable para subida de imágenes
alkemyTech/OT275-server pull request #39
Opened 2022-09-02 00:01 UTC by Sieglind

# [OT275-40](https://alkemy-labs.atlassian.net/browse/OT275-40)

Created ImageDelegate class  and IUploadImage interface to allow the upload of images to the AWS S3 Service

### HOW HAS THIS BEEN TESTED?

Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration.

- [ ] Postman.
- [ ] Unit test.
- [ ] Integration test.
- [ ] No testing required (only applies for tech task).

**Test Configuration**:

* ...
* ...

**Screenshots**:
Implemente este codigo para testear la subida de la imagen:
![image](https://user-images.githubusercontent.com/73443385/188031802-51919b5e-9551-4bb1-bace-9de6724a85fd.png)

El metodo devuelve esta URL:
![image](https://user-images.githubusercontent.com/73443385/188031875-4e0bf4bf-2009-42a5-ae17-7ddd437d8b2c.png)

La imagen se encuentra alojada en el servicio, la URL coincide con la emitida en el LOG
![image](https://user-images.githubusercontent.com/73443385/188031943-7d567c28-167a-41bc-ac21-a8ab32697808.png)

* ....

### CHECKLIST

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added the new resource in the Postman Collection file.

2022-09-02 09:06 UTC, mkain0 requested changes

2022-09-02 09:06 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/config/aws/delegate/ImageDelegate.java
> +  private static final String AMAZON_PART = ".s3.amazonaws.com/";
READ/REVIEW DOCUMENTATION: Esto valores hardcodeados funcionan por un tiempo mientras AWS no se le ocurra modificar la URL. Para esto el SDK de AWS tiene métodos que devuelven la url de un object.

2022-09-02 09:06 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/config/aws/delegate/ImageDelegate.java
> +        metadata);
Falta setear el ACL.

2022-09-02 09:06 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/delegate/IUploadImage.java
> +  String upload(InputStream inputStream, String contentType, String fileName);
SOLID: Todos estos parámetros representan algo que se puede abstraer.

2022-09-02 09:06 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/config/aws/delegate/ImageDelegate.java
> +package com.alkemy.ong.infrastructure.config.aws.delegate;
TRIVIAL: podría estar directo en el package aws. No es necesario crear un package extra ya que solo hay dos clases.

2022-09-02 16:12 UTC, Sieglind commented on src/main/java/com/alkemy/ong/application/service/delegate/IUploadImage.java
> +  String upload(InputStream inputStream, String contentType, String fileName);
Debería crear una clase de dominio que represente el contenido de una petición de upload?

2022-09-02 17:15 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/delegate/IUploadImage.java
> +  String upload(InputStream inputStream, String contentType, String fileName);
Una interfaz. Revisa el repo de la meeting de abstracción.

2022-09-02 22:57 UTC, Sieglind commented
Actualize las evidencias del funcionamiento del código

2022-09-04 18:38 UTC, mkain0 approved these changes

2022-09-04 18:38 UTC, mkain0 approved these changes

2022-09-04 18:39 UTC, merged