OT275-30: Add welcome email template
alkemyTech/OT275-server pull request #41
Opened 2022-09-02 14:03 UTC by r1ckt

# [Ticket OT275-30](https://alkemy-labs.atlassian.net/browse/OT275-30)

- Added file welcome-email.html (template)
- Added welcome email class
- Added IContact interface
- Added SocialNetwork class to apply SOLID

### HOW HAS THIS BEEN TESTED?

Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration.

- [ ] Postman.
- [ ] Unit test.
- [ ] Integration test.
- [ ] No testing required (only applies for tech task).

**Test Configuration**:

* ...
* ...

**Screenshots**:
![Captura de pantalla_2022-09-02_09-47-00](https://user-images.githubusercontent.com/96498642/188165954-1db33d9d-458e-438d-af96-5819b14e9b22.png)

### CHECKLIST

- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added the new resource in the Postman Collection file.

2022-09-02 14:24 UTC, r1ckt commented on src/main/java/com/alkemy/ong/application/util/template/WelcomeEmailTemplate.java
> +      "src/main/resources/template/welcome-email.html";
Esto no se si esta bien, creo que deberia haberle hecho un enum donde se guarden los path de los html, para que quede mas presentable

2022-09-02 15:47 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/util/template/WelcomeEmailTemplate.java
> +      "src/main/resources/template/welcome-email.html";
Esto no es correcto. Existen métodos / clases para levantar los archivos del resource package.

2022-09-02 16:11 UTC, mkain0 requested changes

2022-09-02 16:11 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/util/IMailSender.java
> +  void send(IMail mail) throws IOException;
REVERT: No hay motivos para modificar la firma de esta interfaz. 

Cualquier implementación de este método no puede tirar IOException. Ya sabemos que las excepciones que surgen de el consumo/procesamiento de un servicio externo deben ser wrapeadas en una exception mas genérica.

2022-09-02 16:11 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/config/sendgrid/SendGridUtils.java
> +  public void send(IMail mail) throws IOException {
REVERT: No hay motivos para modificar la firma. Comentario en IMailSender.java

2022-09-02 16:11 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/util/template/WelcomeEmailTemplate.java
> +  private final Organization organization;
Esta interfaz no cumple ninguna función con el código implementado de esta forma.

2022-09-02 16:11 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/util/template/WelcomeEmailTemplate.java
> +    return this.setContent(Files.readString(Path.of(FILE_WELCOME_EMAIL_HTML)));
Esta no es la forma correcta de levantar cosas del resource package. 

`Foo.class.getClassLoader().getResourceAsStream("file.extension");`

o

`getClass().getClassLoader().getResource("file.extension");`

2022-09-02 16:11 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/util/template/WelcomeEmailTemplate.java
> +            organization.getSocialNetwork().getLinkedinUrl());
Si socialNetwork es null, esto lanza NPE.

2022-09-02 16:11 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/util/template/WelcomeEmailTemplate.java
> +    return organization.getName();
El subject es el asunto del mensaje, el organization name, no es un subject muy descriptivo...

2022-09-02 19:35 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/util/template/WelcomeEmailTemplate.java
> +  private final Organization organization;
Discutido en la daily. Esta interfaz esta correcta. Cuando hice la review no interprete correctamente el objetivo de la interfaz. Quizás hubiese sido más claro si se llamará IAddressContact

2022-09-04 18:54 UTC, mkain0 approved these changes

2022-09-04 18:55 UTC, merged