OT275-85: Agregar documentación con Swagger
alkemyTech/OT275-server pull request #55
Opened 2022-09-06 20:31 UTC by Sieglind

# [OT275-85](https://alkemy-labs.atlassian.net/browse/OT275-85)

Added basic documentation for the project, enabled access thru antMatchers

### HOW HAS THIS BEEN TESTED?

No tests were neede for this task

- [ ] Postman.
- [ ] Unit test.
- [ ] Integration test.
- [ ] No testing required (only applies for tech task).

**Test Configuration**:

* ...
* ...

**Screenshots**:
![image](https://user-images.githubusercontent.com/73443385/188732309-9abeb765-b3e1-4e01-aa7d-ecf2b3e27eda.png)

### CHECKLIST

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added the new resource in the Postman Collection file.

2022-09-07 16:37 UTC, mkain0 requested changes

2022-09-07 16:37 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java
> +  private static final String DOCUMENTATION_PATH = "/api/**";
Esta configuración permite que cualquier cosa que comience con /api sea accesible sin credenciales. Se debe especificar las rutas que se quiere hacer publicas, caso contrario, como las apis suelen tener un path= api/v{nro}, esto mala configuración haría a todos los endpoints publicos.

2022-09-07 16:37 UTC, mkain0 commented on src/main/resources/static/documentation.yaml
> +      bearerFormat: JWT
Esto agrega el authorize a la UI, pero no lo hace funcional. Falta setear los security requirements.

2022-09-07 19:53 UTC, Sieglind commented on src/main/resources/static/documentation.yaml
> +      bearerFormat: JWT
Esto se refiere a los security requirements de cada endpoint? Entendi que eso contaba como "generar documentacion extra"

2022-09-07 21:07 UTC, mkain0 commented on src/main/resources/static/documentation.yaml
> +      bearerFormat: JWT
El security requirements no es necesariamente por cada endpoint. Puede ser genérico aplicado a todos los endpoints. Sin el security requirements, tus botones de try no van a funcionar por mas que le pases el JWT en el botón de authorize.

2022-09-08 09:32 UTC, mkain0 commented
@Sieglind Los cambios aplicados fixean el issue en la security de las URLs, pero este swagger sigue siendo no funcional. 

`https://github.com/OAI/OpenAPI-Specification/blob/3.1.0/versions/3.1.0.md#securityRequirementObject`

2022-09-09 09:40 UTC, merged