OT275-77: Endpoint Creación Comentarios
alkemyTech/OT275-server pull request #56
Opened 2022-09-07 03:04 UTC by Sieglind

# [OT275-77](https://alkemy-labs.atlassian.net/browse/OT275-77)

Comment creation endpoint added, validations applied

### HOW HAS THIS BEEN TESTED?

Using postman a POST request has been sent to the endpoint and the results were verified in the database

- [x ] Postman.
- [ ] Unit test.
- [ ] Integration test.
- [ ] No testing required (only applies for tech task).

**Test Configuration**:

No special configuration was needed for the test

**Screenshots**:
With no comments in the database
![image](https://user-images.githubusercontent.com/73443385/188778243-09896709-7b8b-4990-a2fb-22711a0bbd09.png)
The code validates for null user and news id, and for null or empty body content
![image](https://user-images.githubusercontent.com/73443385/188778401-97d5195e-d792-46fc-8941-3f9a577d6a0e.png)
Given a correct body format the response is as follows:
![image](https://user-images.githubusercontent.com/73443385/188779134-63850d10-6e57-4624-8bdd-af794bf384e1.png)
And the  database shows the results:
![image](https://user-images.githubusercontent.com/73443385/188779450-1ce3b614-9daa-4196-8aaa-fdfe9e6e979e.png)

### CHECKLIST

- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added the new resource in the Postman Collection file.

2022-09-07 08:53 UTC, mkain0 requested changes

2022-09-07 08:53 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/CreateCommentUseCaseService.java
> +  public Comment create(Comment comment, Identifiable<Long> userId, Identifiable<Long> newsId) {
CODE SMELL: 

- userId es un atributo de User
- newsId es un atributo de News
- News y User son atributos de Comment.

2022-09-07 08:53 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/CreateCommentUseCaseService.java
> +public class CreateCommentUseCaseService implements ICreateCommentUseCase {
PERFORMANCE: la lógica empleada en esta clase esta realizando 4 queries para búsqueda cuando se puede resolver con solo 2.

2022-09-07 08:53 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/usecase/ICreateCommentUseCase.java
> +  Comment create(Comment toDomain, Identifiable<Long> userId, Identifiable<Long> newsId);
CODE SMELL: mencionado en la implementación de esta clase.

2022-09-07 08:53 UTC, mkain0 commented on src/main/java/com/alkemy/ong/domain/News.java
> +  private Long createTimestamp;
Este atributo no se requiere en el dominio.

2022-09-07 08:53 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/database/mapper/NewsEntityMapper.java
> +    news.setCreateTimestamp(entity.getCreateTimestamp().getTime());
Este atributo no se debe propagar.

2022-09-07 08:53 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/database/mapper/NewsEntityMapper.java
> +    entity.setCreateTimestamp(new Timestamp(news.getCreateTimestamp()));
Este atributo no se debe propagar.

2022-09-07 08:53 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/mapper/CreateCommentMapper.java
> +  }
REVIEW THIS LOGIC: revisar en base al code smell reportado.

2022-09-07 08:53 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/resource/CommentResource.java
> +    return ResponseEntity.ok(response);
200 no es el status code correcto para una operación de creación.

2022-09-07 08:53 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/request/CreateCommentRequest.java
> +      message = "Comment body must only contain letters and numbers, and not be empty")
NO CUMPLE CON EL AC: "caracteres alfanuméricos"

2022-09-07 08:55 UTC, mkain0 commented
NO CUMPLE AC: falta "COMO usuario estándar"

2022-09-07 21:13 UTC, mkain0 requested changes

2022-09-07 21:13 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/CreateCommentUseCaseService.java
> +    News news = newsRepository.get(() -> comment.getAssociatedNews().getId());
MINOR: si user es null, no voy a hacer otra request que afecta el tiempo de respuesta. Directamente lanzo la exception.

2022-09-07 21:13 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/mapper/CreateCommentMapper.java
> +    response.setCreatedBy(comment.getCreatedBy().getFirstName());
CreatedBy debe ser la combinación del firstName + el lastName.

2022-09-07 21:13 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/request/CreateCommentRequest.java
> +  @NotNull(message = "User Id must not be null")
Este mensaje sigue estando erroneo.

2022-09-07 21:14 UTC, mkain0 commented on src/main/java/com/alkemy/ong/domain/News.java
> +  private Long createTimestamp;
SIGUE SIN RESOLVER DESPUES DE LA SEGUNDA REVIEW.

2022-09-07 21:47 UTC, Sieglind commented on src/main/java/com/alkemy/ong/domain/News.java
> +  private Long createTimestamp;
Cuando resolví los conflictos elegir quedarme con el "News" que había creado Ezequiel Villafañe para resolver su ticket, pero por alguna no se commiteo junto con los demás cambios que hice al corregir el PR

2022-09-07 22:05 UTC, Sieglind commented on src/main/java/com/alkemy/ong/domain/News.java
> +  private Long createTimestamp;
https://github.com/alkemyTech/OT275-server/blob/OT275-77/src/main/java/com/alkemy/ong/domain/News.java
Pero el archivo que está presente es idéntico al de main ahora

2022-09-08 08:27 UTC, mkain0 approved these changes

2022-09-08 08:27 UTC, merged