OT275-80
alkemyTech/OT275-server pull request #60
Opened 2022-09-07 20:16 UTC by FedericoRohr

# [OT275-80](https://alkemy-labs.atlassian.net/browse/OT275-80)

-Added classes IGetNewsWithCommentsUseCase, GetNewsWithCommentsUseCaseService (Bean created), 
-Added mappers 
- Extend Domain News and create GetNewsWithCommentsResponse
- Added endpoint and method with security config
- Create Repository Query and methods 

### HOW HAS THIS BEEN TESTED?

Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration.

- [X] Postman.
- [ ] Unit test.
- [ ] Integration test.
- [ ] No testing required (only applies for tech task).

**Test Configuration**:

* ...
* ...

**Screenshots**:
![image](https://user-images.githubusercontent.com/104379574/188968157-7cd7bc03-a5d2-4eed-b111-52ff576264f0.png)

### CHECKLIST

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added the new resource in the Postman Collection file.

2022-09-07 21:32 UTC, mkain0 requested changes

2022-09-07 21:32 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/config/spring/security/SecurityConfig.java
> +        .hasAnyRole(Role.USER.name(), Role.ADMIN.name())
El AC dice: "COMO usuario estándar"

2022-09-07 21:32 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/resource/NewsResource.java
> +  private final IGetNewsWithCommentsUseCase getNewsWithCommentsUseCase;
TRIVIAL: la definición de getWithComments también podría existir en IGetNewsUseCase.

2022-09-07 21:32 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/GetNewsWithCommentsUseCaseService.java
> +    return newsRepository.getWithComments(identifiable);
Qué sucede si el ID de news no existe en la base de datos o fue eliminado?

2022-09-07 21:32 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/database/mapper/CommentEntityMapper.java
> +  }
Esto ya no es responsabilidad de una tercera clase, una tuple puede estar organizada de cualquier forma. Por lo tanto, este mapeo es responsabilidad del repositorio que es quien conoce en que orden se seleccionaron las columnas en la query.

2022-09-07 21:32 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/database/mapper/NewsEntityMapper.java
> +  }
Esto ya no es responsabilidad de una tercera clase, una tuple puede estar organizada de cualquier forma. Por lo tanto, este mapeo es responsabilidad del repositorio que es quien conoce en que orden se seleccionaron las columnas en la query.

2022-09-08 01:22 UTC, FedericoRohr commented on src/main/java/com/alkemy/ong/infrastructure/rest/resource/NewsResource.java
> +  private final IGetNewsWithCommentsUseCase getNewsWithCommentsUseCase;
Si , lo hice en entra clase para evitar conflictos futuros con otros tickets

2022-09-08 02:08 UTC, FedericoRohr commented on src/main/java/com/alkemy/ong/infrastructure/database/mapper/CommentEntityMapper.java
> +  }
Entiendo el punto pero me resulta raro que el repositorio se encargue de realizar tareas de mappeo

2022-09-08 09:11 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/database/mapper/CommentEntityMapper.java
> +  }
Si lo dejo en el mapper, cualquier query que haga utilizando tuplas, tiene que poder ser convertida a un objeto de dominio Comment con este método y eso no es cierto, porque puedo hacer `SELECT id FROM NewsEntity` o `SELECT description, body FROM NewsEntity INNER JOIN CommentEntity` o `SELECT id, description FROM NewsEntity` y todos devolver tuplas, sin embargo, este mapper me estaría devolviendo objetos de dominio erroneos.

Adicionalmente, si estuvieras haciendo TDD, se vería a primeras de quién es responsabilidad este mappeo. Y si no se hace TDD, y se hace un unit test, el unit test muestra que el costo de testear esta funcionalidad es demasiado algo y por lo tanto se debe refactorizar para que el test sea lo más sencillo/simple para protegerse ante cambios en el código.

2022-09-08 09:15 UTC, mkain0 approved these changes

2022-09-08 09:19 UTC, merged