OT275 - 48: Endpoint Actualización Novedades
alkemyTech/OT275-server pull request #72
Opened 2022-09-12 19:44 UTC by LAYALA09

# [TOT275 - 48](https://alkemy-labs.atlassian.net/browse/OT275 - 48)

Adde Endpoint Put de News.

### HOW HAS THIS BEEN TESTED?

Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration.

- [x] Postman.
- [ ] Unit test.
- [ ] Integration test.
- [ ] No testing required (only applies for tech task).

**Test Configuration**:

* ...
* ...

**Screenshots**:
![CREACION DE NEWS](https://user-images.githubusercontent.com/68357688/189741836-a96f77d2-4522-4d03-b19e-1d6fe59ab9b3.jpg)
*
![exceptionnews](https://user-images.githubusercontent.com/68357688/189741893-90ab830a-7d93-46f9-9c7b-0103f5aa7140.jpg)

* ....
![ACTUALIZACION NEW](https://user-images.githubusercontent.com/68357688/189741938-9d2a3af0-8cae-4db3-86ee-04d066b53411.jpg)

### CHECKLIST

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added the new resource in the Postman Collection file.

2022-09-12 20:00 UTC, mkain0 requested changes

2022-09-12 20:00 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/UpdateNewsUseCaseService.java
> +      news.setCategory(category);
TRIVIAL: toda esta lógica no era necesaria para el scope del ticket.

2022-09-12 21:02 UTC, LAYALA09 commented on src/main/java/com/alkemy/ong/infrastructure/rest/response/UpdateNewsResponse.java
> +public class UpdateNewsResponse {
Hice otra clase, ya que en el ticket se solicita que  el response devuelva text e image, no content e  imageUrl.

2022-09-12 21:22 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/response/UpdateNewsResponse.java
> +public class UpdateNewsResponse {
@LAYALA09 Ahhhhh... tenes razón! Hay un error en el ticket xD 
La response debe ser la entidad actualizada, por lo tanto, debe contener todos los datos de la entidad: id, name, content, imageUrl y category -- optional.

2022-09-12 21:23 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/response/UpdateNewsResponse.java
> +public class UpdateNewsResponse {
Esto me lleva a que también el request body esta mal, nos esta faltando el imageUrl en la request. Caso contrario, siempre que se actualice la entidad se va a setear en null y eso no estaría bien.

2022-09-12 21:57 UTC, LAYALA09 commented on src/main/java/com/alkemy/ong/infrastructure/database/repository/NewsRepository.java
> +import java.util.Optional;
Fue importado cuando se creó News. 

@Query("SELECT n FROM NewsEntity n WHERE n.softDeleted = false AND n.newsId = :id")
  Optional<NewsEntity> exists(@Param("id") Long id);

2022-09-13 08:34 UTC, mkain0 approved these changes

2022-09-13 08:35 UTC, merged