OT275-78: Endpoint Actualización Comentarios
alkemyTech/OT275-server pull request #76
Opened 2022-09-13 18:40 UTC by Sieglind

# [OT275-78](https://alkemy-labs.atlassian.net/browse/OT275-78)

Created endpoint to update comments

### HOW HAS THIS BEEN TESTED?

This code has been tested using Postman and a Unit Test

- [ ] Postman.
- [ ] Unit test.
- [ ] Integration test.
- [ ] No testing required (only applies for tech task).

**Test Configuration**:
No additional configuration was needed to perform this tests

**Screenshots**:
Given comments stored in the database:
![image](https://user-images.githubusercontent.com/73443385/189983127-1695fb90-6700-4452-8b03-e91642d2d187.png)
We try to update one without proper authorization:
![image](https://user-images.githubusercontent.com/73443385/189983517-5a24d4f4-c1db-467d-bfb6-3d22c480ca0d.png)
Now we try to update a comment from the same user:
![image](https://user-images.githubusercontent.com/73443385/189983708-d63f10d9-63e0-43f0-9e91-b3c97045bcdd.png)
And now the comment contents have been updated:
![image](https://user-images.githubusercontent.com/73443385/189983880-42754625-ed4b-41ea-976b-ceb062915173.png)

### CHECKLIST

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added the new resource in the Postman Collection file.

2022-09-13 22:37 UTC, mkain0 requested changes

2022-09-13 22:37 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/mapper/comment/CommentMapper.java
> +public class CommentMapper {
UpdateCommentMapper

2022-09-13 22:37 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/comment/UpdateCommentUseCase.java
> +    return commentRepository.update(comment);
Perdió la news y perdió la user?

2022-09-13 22:37 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/mapper/comment/CommentMapper.java
> +  }
NO REQUIRED: no hay lista que mapear.

2022-09-13 22:37 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/mapper/comment/CommentMapper.java
> +  }
Devolver el objeto completo: se puede extender de GetCommentMapper para reutilizar el código.

2022-09-13 22:37 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/resource/CommentResource.java
> +  private final CommentMapper commentMapper;
RENAME ATTRIBUTE: una vez renombrada la clase.

2022-09-13 22:37 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/response/comment/CommentResponse.java
> +  private String body;
NO REQUIRED: será reemplazada por GetCommentResponse

2022-09-14 02:22 UTC, Sieglind commented on src/main/java/com/alkemy/ong/application/service/comment/UpdateCommentUseCase.java
> +    return commentRepository.update(comment);
![image](https://user-images.githubusercontent.com/73443385/190044229-81c3293d-4865-4938-a54a-84967af2edd5.png)
News y User siguen en la base de datos

2022-09-14 02:27 UTC, Sieglind commented on src/main/java/com/alkemy/ong/infrastructure/database/mapper/CommentEntityMapper.java
> +    }
![image](https://user-images.githubusercontent.com/73443385/190044815-9eb8e5f2-e09a-48c3-94f6-998e36a202e6.png)

2022-09-14 02:32 UTC, Sieglind commented on src/main/java/com/alkemy/ong/infrastructure/rest/mapper/comment/CommentMapper.java
> +  }
Tratar de devolver  el objeto completo me genera el mismo inconveniente que con el atributo "CreateTimestamp", solo los campos actualizados son devueltos

2022-09-14 09:07 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/comment/UpdateCommentUseCase.java
> +    return commentRepository.update(comment);
@Sieglind Si, anoche me encontré con quecuando definimos el join lo hicimos como `updatable = false`, entonces no sobreescribe el user ni la news.

2022-09-14 09:19 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/rest/mapper/comment/CommentMapper.java
> +  }
1. Hay un mistake en mi primer comentario, se debe extender de CreateCommentMapper para devolver la entidad completa.
2. El inconveniente que tenes tiene que ser un data issue. No hay motivos para que el createTimestamp vuelva en null cuando se realiza el save.

2022-09-14 12:27 UTC, Sieglind commented on src/main/java/com/alkemy/ong/infrastructure/database/mapper/CommentEntityMapper.java
> +    }
Insert en la base de datos

2022-09-14 21:04 UTC, mkain0 approved these changes

2022-09-14 21:05 UTC, mkain0 commented
@Sieglind Hice algunos cambios extras, pero el problema que tenias se resuelve con el ultimo commit: [6edd8df](https://github.com/alkemyTech/OT275-server/pull/76/commits/6edd8dfbbb8795510bb3b6bef0056173c4fd8e94)

2022-09-14 21:05 UTC, merged

2022-09-14 21:35 UTC, Sieglind commented
Gracias Magali, ahora me pongo a revisar que es lo que sucedía con el método