OT275-18: Created User & his repository
alkemyTech/OT275-server pull request #8
Opened 2022-08-19 22:01 UTC by r1ckt

# [Ticket OT275-18](https://alkemy-labs.atlassian.net/browse/OT275-18)

- UserEntity
- IUserRepository
- UserRepository (implementation)
- IUserSpringRepository

### HOW HAS THIS BEEN TESTED?

- [ ] Postman.
- [ ] Unit test.
- [ ] Integration test.
- [X] No testing required (only applies for tech task).

### CHECKLIST

- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added the new resource in the Postman Collection file.

2022-08-20 10:32 UTC, mkain0 requested changes

2022-08-20 10:32 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/database/entity/UserEntity.java
> +@SQLDelete(sql = "UPDATE user SET soft_deleted = true WHERE user_id = ?")
Principio de única responsabilidad comentado en otros PRs.

2022-08-20 10:32 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/database/entity/UserEntity.java
> +  @GeneratedValue(strategy = IDENTITY)
MINOR Style: `strategy = GenerationType.IDENTITY` para ser consistente con la forma en que otros miembros del equipo escribieron las entidades.

2022-08-20 10:32 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/database/entity/UserEntity.java
> +  private Long userId;
Falta definir el `@Column`.

2022-08-20 10:32 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/database/entity/UserEntity.java
> +  @OneToOne(fetch = LAZY, cascade = MERGE)
Esta relación no es correcta. Un usuario tiene un único role, pero un role puede pertenecer a más de un usuario.
@ManyToOne

2022-08-20 10:32 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/database/entity/UserEntity.java
> +  @OneToOne(fetch = LAZY, cascade = MERGE)
MINOR: revisar el style del fetch y cascade.

2022-08-20 10:32 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/database/entity/UserEntity.java
> +public class UserEntity implements UserDetails {
No es parte del scope de este ticket aplicar UserDetails sobre la entidad User.

2022-08-20 14:28 UTC, mkain0 requested changes

2022-08-20 14:28 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/database/entity/UserEntity.java
> +  }
MINOR: No es parte del scope de este ticket.

2022-08-20 14:28 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/database/entity/UserEntity.java
> +  @ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.MERGE)
En el README hay links que explican los diferentes fetch type y sus ventajas y desventajas.

También fue conversado en la daily > en caso de que necesites discutirlo con tus compañeros.

2022-08-20 15:37 UTC, r1ckt commented on src/main/java/com/alkemy/ong/infrastructure/database/entity/UserEntity.java
> +  @ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.MERGE)
Se me escapó lo del eager, ahi lo arreglo. Por lo que lei en el readme y otras fuentes conviene usar Lazy la mayoria de las veces, no?

2022-08-20 16:05 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/database/entity/UserEntity.java
> +  @ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.MERGE)
@r1ckt , como mencioné en mi comentario anterior. El primer paso es discutirlo entre ustedes, y después consultarme a mí. Esto ya fue discutido con tus compañeros y cualquiera de los que estuvo presente en la daily puede ayudarte con tu pregunta.

2022-08-21 00:11 UTC, mkain0 approved these changes

2022-08-21 00:12 UTC, merged